# Generated by Django 5.0.1 on 2024-01-31 17:09

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Search',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(default='NewSearch', max_length=50, verbose_name='Name')),
                ('link', models.TextField(verbose_name='Link')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Date of search')),
                ('ready', models.IntegerField(default=0, verbose_name='Ready')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Search',
                'verbose_name_plural': 'Searches',
            },
        ),
        migrations.CreateModel(
            name='ProfileInfo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('link', models.CharField(max_length=50, verbose_name='Link')),
                ('first_name', models.CharField(max_length=50, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=50, verbose_name='Last Name')),
                ('bdate', models.DateTimeField(verbose_name='Birth Date')),
                ('interests', models.TextField(verbose_name='Interests')),
                ('books', models.TextField(verbose_name='Books')),
                ('tv', models.TextField(verbose_name='TV')),
                ('games', models.TextField(verbose_name='Games')),
                ('movies', models.TextField(verbose_name='Movies')),
                ('activities', models.TextField(verbose_name='Activities')),
                ('music', models.TextField(verbose_name='Music')),
                ('status', models.TextField(verbose_name='Status')),
                ('military', models.IntegerField(verbose_name='Military')),
                ('university_name', models.TextField(verbose_name='University Name')),
                ('faculty', models.TextField(verbose_name='Faculty')),
                ('home_town', models.CharField(max_length=50, verbose_name='Home Town')),
                ('relation', models.TextField(verbose_name='Relation')),
                ('sex', models.IntegerField(verbose_name='Sex')),
                ('about', models.TextField(verbose_name='About')),
                ('timezone', models.CharField(max_length=10, verbose_name='Timezone')),
                ('friends_count', models.IntegerField(verbose_name='Friends count')),
                ('followers_count', models.IntegerField(verbose_name='Followers count')),
                ('groups', models.TextField(verbose_name='Groups')),
                ('posts', models.TextField(verbose_name='Posts')),
                ('comments', models.TextField(verbose_name='Comments')),
                ('alcohol', models.CharField(max_length=50, verbose_name='Alcohol')),
                ('life_main', models.CharField(max_length=50, verbose_name='Life Main')),
                ('people_main', models.CharField(max_length=50, verbose_name='People Main')),
                ('political', models.CharField(max_length=50, verbose_name='Political')),
                ('religion', models.CharField(max_length=50, verbose_name='Religion')),
                ('smoking', models.CharField(max_length=50, verbose_name='Smoking')),
                ('connected_search', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='data_collector.search')),
            ],
            options={
                'verbose_name': 'ProfileInfo',
                'verbose_name_plural': 'ProfileInfos',
            },
        ),
        migrations.CreateModel(
            name='GroupInfo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('posts', models.TextField(verbose_name='Posts')),
                ('description', models.TextField(verbose_name='Description')),
                ('connected_search', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='data_collector.search')),
            ],
            options={
                'verbose_name': 'GroupInfo',
                'verbose_name_plural': 'GroupInfos',
            },
        ),
    ]
