# Generated by Django 5.0.1 on 2024-01-23 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_collector', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='search',
            old_name='user_id',
            new_name='created_by',
        ),
    ]
